tap "chrokh/tap"
tap "fabianishere/personal"
tap "goles/battery"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "systemist/formulae", "https://github.com/systemist/homebrew-formulae.git"
tap "koekeishiya/formulae"
tap "microsoft/git"
tap "nodenv/nodenv"
tap "thoughtbot/formulae"
brew "automake"
brew "openssl@1.1"
brew "readline"
brew "python@3.8"
brew "awscli"
brew "bats"
brew "glib"
brew "circleci"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "dialog"
brew "diff-so-fancy"
brew "direnv"
brew "dnsmasq", restart_service: true
brew "emojify"
brew "exercism"
brew "icu4c"
brew "ffmpeg"
brew "findutils"
brew "gawk"
brew "gdb"
brew "gist"
brew "git"
brew "git-crypt"
brew "gnu-sed"
brew "go"
brew "grep"
brew "highlight"
brew "htop"
brew "hub"
brew "imagemagick"
brew "jq"
brew "librdkafka"
brew "kafkacat"
brew "libssh"
brew "make"
brew "mas"
brew "moreutils"
brew "neovim"
brew "netcat"
brew "node"
brew "nodenv"
brew "tmux"
brew "overmind"
brew "pidof"
brew "postgresql", restart_service: true
brew "pstree"
brew "ruby-build"
brew "rbenv"
brew "rbenv-bundler"
brew "rbenv-ctags"
brew "rbenv-default-gems"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rmtrash"
brew "ruby"
brew "socat"
brew "ssh-copy-id"
brew "starship"
brew "terraform"
brew "tig"
brew "tmate"
brew "tree"
brew "vim"
brew "watch"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "chrokh/tap/base16-manager"
brew "fabianishere/personal/pam_reattach"
brew "goles/battery/battery"
brew "heroku/brew/heroku"
brew "systemist/formulae/slack-cli"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "nodenv/nodenv/nodenv-default-packages"
brew "thoughtbot/formulae/parity"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "1password-cli"
cask "airtable"
cask "alacritty"
cask "alfred"
cask "anylist"
cask "appcleaner"
cask "authy"
cask "backblaze"
cask "bartender"
cask "base"
cask "bookends"
cask "carbon-copy-cloner"
cask "charles"
cask "choosy"
cask "chromedriver"
cask "colorpicker-skalacolor"
cask "dash4"
cask "devonthink"
cask "docker"
cask "dropbox"
cask "encryptme"
cask "firefox"
cask "focus"
cask "font-fontawesome"
cask "git-credential-manager-core"
cask "google-chrome"
cask "hazel"
cask "kaleidoscope"
cask "karabiner-elements"
cask "kindle"
cask "kinesis-smart-set"
cask "logitech-options"
cask "marked"
cask "miro"
cask "monodraw"
cask "muzzle"
cask "nightowl"
cask "notion"
cask "omnigraffle"
cask "omniplan"
cask "paw"
cask "postico"
cask "quitter"
cask "rocket"
cask "screenflow6"
cask "scrivener"
cask "send-to-kindle"
cask "sf-symbols"
cask "sketch"
cask "slack"
cask "spotify"
cask "thingsmacsandboxhelper"
cask "timeular"
cask "tinderbox"
cask "toggl"
cask "tripmode"
cask "vimr"
mas "1Blocker", id: 1107421413
mas "A Companion for SwiftUI", id: 1485436674
mas "Airmail", id: 918858936
mas "DaisyDisk", id: 411643860
mas "Delicious Library", id: 635124250
mas "Deliveries", id: 924726344
mas "Drafts", id: 1435957248
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Instapaper", id: 1481302432
mas "Keynote", id: 409183694
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1449412482
mas "ScanSnap Cloud", id: 1211119808
mas "Sequence Diagram", id: 1195426709
mas "Shush", id: 496437906
mas "Sip", id: 507257563
mas "Spectrum", id: 518156125
mas "Things", id: 904280696
mas "ToothFairy", id: 1191449274
mas "Transmit", id: 403388562
mas "Ulysses", id: 1225570693
mas "Xcode", id: 497799835
