#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "Neptr"
sudo scutil --set HostName "Neptr"
sudo scutil --set LocalHostName "Neptr"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "Neptr"
