#!/usr/bin/env bash
COPY_ALWAYS="tag-mac/Library/Scripts/**/*"
DOTFILES_DIRS="$HOME/.dotfiles"
EXCLUDES="script/* fonts/* Brewfile README.md LICENSE decryption-status"
TAGS="encrypted"
UNDOTTED="Library"
