#!/bin/sh

case "$OSTYPE" in
  "darwin"*)
    RCM_OS_TAG="mac"
    export UNDOTTED="Library"
    ;;
  "linux-gnu"*)
    RCM_OS_TAG="linux"
    ;;
  *)
    echo "Unsupported OS $OSTYPE" >&2
    exit 1
    ;;
esac

export DOTFILES_DIRS="$HOME/.dotfiles"
export SYMLINK_DIRS="agents/skills/*"
export EXCLUDES="script/* README.md LICENSE claude-plugins docs docs/* test test/* *__pycache__*"
export TAGS="$RCM_OS_TAG"
