#!/bin/bash
EXCLUDES="setup-mac setup-linux README.md LICENSE"
SYMLINK_DIRS="rbenv/plugins vim/UltiSnips Library/Scripts/AddFilesToThings.app"
DOTFILES_DIRS="$HOME/.dotfiles"
UNDOTTED="Library"
TAGS="encrypted"
COPY_ALWAYS="Library/Fonts/*"
