#!/bin/bash

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    export PATH="/usr/local/bin:$PATH"
fi

if ! command -v mas >/dev/null; then
  brew install mas
fi

# mas signin is currently broken
# https://github.com/mas-cli/mas/issues/164
# if ! mas account >/dev/null; then
#   echo -n "Mac App Store Password:"
#   read -rs password
#   echo
#   mas signin "jacob@jacobsmith.io" "$password"
# fi

if [ ! -f /Library/Developer/CommandLineTools/usr/bin/git ]; then
  echo "Installing XCode..."
  sudo xcodebuild -license accept
fi

echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=- <<EOF
tap "homebrew/services"

tap "Goles/battery"
brew "battery"

tap "nodenv/nodenv"
brew "nodenv-default-packages"

tap "thoughtbot/formulae"
brew "rcm"

tap "chrokh/tap"
brew "base16-manager"

brew "cmake"
brew "coreutils"
brew "ctags"
brew "dialog"
brew "diff-so-fancy"
brew "emojify"
brew "exercism"
brew "findutils"
brew "fzf"
brew "gawk"
brew "gdb"
brew "gist"
brew "git"
brew "git-crypt"
brew "go"
brew "gpg"
brew "hub"
brew "jq"
brew "kafkacat"
brew "neovim"
brew "netcat"
brew "nodenv"
brew "openssl"
brew "overmind"
brew "python"
brew "rbenv"
brew "rbenv-bundler"
brew "rbenv-ctags"
brew "rbenv-default-gems"
brew "reattach-to-user-namespace"
brew "rmtrash"
brew "ruby-build"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tig"
brew "tmate"
brew "tmux"
brew "toggl"
brew "tree"
brew "vim"
brew "watch"
brew "watchman"
brew "zsh"

tap "caskroom/fonts"
cask "font-firacode-nerd-font"

cask "1password"
cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "base"
cask "choosy"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "hazel"
cask "iterm2"
cask "kaleidoscope"
cask "marked"
cask "monodraw"
cask "muzzle"
cask "nightowl"
cask "paw"
cask "postico"
cask "quickbooks-online"
cask "quitter"
cask "rocket"
cask "sketch"
cask "spotify"
cask "thingsmacsandboxhelper"
cask "timing"
cask "tinderbox"
cask "toggl"
cask "tripmode"
cask "visual-studio-code"

mas '1Blocker', id: 1107421413
mas 'Airmail 3', id: 918858936
mas 'Fantastical 2', id: 975937182
mas 'Magnet', id: 441258766
mas 'ReadKit', id: 588726889
mas 'Things3', id: 904280696
mas 'Trello', id: 1278508951
mas 'iA Writer', id: 775737590
EOF

echo "Cleaning up old Homebrew formulae ..."
brew cleanup
