#!/bin/bash

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
  export PATH="/usr/local/bin:$PATH"
fi

if ! command -v mas >/dev/null; then
  brew install mas
fi

if [ ! -f /Library/Developer/CommandLineTools/usr/bin/git ]; then
  echo "Installing XCode..."
  sudo xcodebuild -license accept
fi

echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=- <<EOF
tap "homebrew/services"

tap "Goles/battery"
brew "battery"

tap "chrokh/tap"
brew "base16-manager"

tap "iakobos/formulae"
cask "consider"
cask "screenflow6"

tap "nodenv/nodenv"
brew "nodenv-default-packages"

tap "thoughtbot/formulae"
brew "rcm"

brew "cmake"
brew "coreutils"
brew "ctags"
brew "dialog"
brew "diff-so-fancy"
brew "emojify"
brew "exercism"
brew "findutils"
brew "fzf"
brew "gawk"
brew "gdb"
brew "gist"
brew "git"
brew "git-crypt"
brew "go"
brew "gpg"
brew "highlight"
brew "hub"
brew "jq"
brew "kafkacat"
brew "neovim"
brew "netcat"
brew "nodenv"
brew "openssl"
brew "overmind"
brew "python"
brew "rbenv"
brew "rbenv-bundler"
brew "rbenv-ctags"
brew "rbenv-default-gems"
brew "reattach-to-user-namespace"
brew "rmtrash"
brew "ruby-build"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tig"
brew "tmate"
brew "tmux"
brew "toggl"
brew "tree"
brew "vim"
brew "watch"
brew "watchman"
brew "zsh"

tap "caskroom/fonts"
cask "font-firacode-nerd-font"

tap "homebrew/cask-drivers"
cask "logitech-options"

cask "1password"
cask "1password-cli"
cask "airtable"
cask "alfred"
cask "anylist"
cask "appcleaner"
cask "backblaze"
cask "bartender"
cask "base"
cask "charles"
cask "choosy"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "hazel"
cask "iterm2"
cask "kaleidoscope"
cask "kindle"
cask "marked"
cask "monodraw"
cask "muzzle"
cask "paw"
cask "postico"
cask "quitter"
cask "rocket"
cask "scrivener"
cask "send-to-kindle"
cask "sketch"
cask "spotify"
cask "timing"
cask "tinderbox"
cask "toggl"
cask "tripmode"

mas '1Blocker', id: 1107421413
mas 'Bear', id: 1091189122
mas 'Copied', id: 1026349850
mas 'Delicious Library', id: 635124250
mas 'Drafts', id: 1435957248
mas 'Fantastical', id: 975937182
mas 'Keep It', id: 1272768911
mas 'Magnet', id: 441258766
mas 'MindNode', id: 1289197285
mas 'Progress Bar', id: 1441939775
mas 'ReadKit', id: 588726889
mas 'ScanSnap Cloud', id: 1211119808
mas 'Shush', id: 496437906
mas 'Things', id: 904280696
mas 'ToothFairy', id: 1191449274
mas 'Ulysses', id: 1225570693
mas 'Xcode', id: 497799835
mas 'iA Writer', id: 775737590
EOF

echo "Cleaning up old Homebrew formulae ..."
brew cleanup
