#!/bin/bash

set -e
sudo apt-get update

sudo apt install -y \
awscli \
cmake \
exuberant-ctags \
dialog \
g++ \
gcc \
gdb \
git-crypt \
golang-go \
make \
neovim \
python3 \
python3-pip \
silversearcher-ag \
tig \
tmate \
tree \
unzip \
zsh \
`# for ruby:` \
libssl-dev \
libreadline-dev \
zlib1g-dev

export PATH="~/.nodenv/bin:~/.rbenv/bin:$PATH"

if ! hash node 2>/dev/null; then
  curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
  sudo apt install -y nodejs
fi

if [ ! -d ~/.nodenv ]; then
  npx @nodenv/nodenv-installer
fi

if [ ! -d ~/.nodenv/plugins/nodenv-default-packages ]; then
  git clone https://github.com/nodenv/nodenv-default-packages.git ~/.nodenv/plugins/nodenv-default-packages
fi

if ! hash base16-manager 2>/dev/null; then
  mkdir -p ~/src
  git clone https://github.com/AuditeMarlow/base16-manager.git ~/src/base16-manager
  pushd ~/src/base16-manager
  sudo make install
  popd
fi

if ! hash diff-so-fancy 2>/dev/null; then
  sudo sh -c "curl https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy -o /usr/local/bin/diff-so-fancy && chmod +x /usr/local/bin/diff-so-fancy"
fi

if ! hash emojify 2>/dev/null; then
  sudo sh -c "curl https://raw.githubusercontent.com/mrowa44/emojify/master/emojify -o /usr/local/bin/emojify && chmod +x /usr/local/bin/emojify"
fi

if ! hash rbenv 2>/dev/null; then
  curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
fi

if [ ! -d ~/.rbenv/plugins/bundler ]; then
  mkdir -p ~/.rbenv/plugins
  git clone https://github.com/carsomyr/rbenv-bundler.git ~/.rbenv/plugins/bundler
fi

if [ ! -d ~/.rbenv/plugins/rbenv-ctags ]; then
  mkdir -p ~/.rbenv/plugins
  git clone git://github.com/tpope/rbenv-ctags.git ~/.rbenv/plugins/rbenv-ctags
fi

if [ ! -d ~/.rbenv/plugins/rbenv-default-gems ]; then
  mkdir -p ~/.rbenv/plugins
  git clone https://github.com/rbenv/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems
fi

if [ ! -d ~/.op ]; then
  curl -o ~/src/op.zip https://cache.agilebits.com/dist/1P/op/pkg/v0.5.5/op_linux_amd64_v0.5.5.zip
  unzip ~/src/op.zip -d ~/.op
fi

if ! hash rcup 2>/dev/null; then
  sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
  sudo apt install -y rcm
fi

echo "running rcup"
RCRC="$HOME/.dotfiles/rcrc" TAGS="linux" rcup
