#!/bin/bash

set -e

if [ ! -f "$HOME/.dotfiles/.git/git-crypt/keys/default" ]; then
  read -p "1Password subdomain: " opsubdomain
  read -p "1Password email: " opemail
  eval $(~/.op/op signin "$opsubdomain.1password.com" "$opemail")

  keyfile=$(mktemp)
  ~/.op/op get document dotfiles.key > $keyfile

  pushd "$HOME/.dotfiles"
  git crypt unlock $keyfile
  popd
fi
