#!/bin/bash
brew bundle --file=- <<EOF
brew youtube-dl

tap "iakobos/formulae"
cask "screenflow6"
cask "the-archive"
cask "timeular"

cask "anylist"
cask "backblaze"
cask "cleanmymac"
cask "epichrome"
cask "gemini"
cask "kindle"
cask "papers"
cask "send-to-kindle"

mas 'Deliveries', id: 924726344
mas 'ScanSnap Cloud', id: 1211119808
EOF
