#!/usr/bin/env bash

set -eo pipefail

PATH="$HOME/.nodenv/bin:$PATH"

echo "Configuring Node ..."

node_version="$(cat "$HOME/.node-version")"
eval "$(nodenv init -)"

if ! nodenv versions | grep -Fq "$node_version"; then
  nodenv install -s "$node_version"
fi

nodenv global "$node_version"
nodenv shell "$node_version"
nodenv default-packages install --all
