#!/usr/bin/env bash

set -eo pipefail

# hooks are executed with pwd set to dirname of file
decryption_status_path="../../tag-encrypted/decryption-status"

if [[ "$(cat "$decryption_status_path")" != "1" ]]; then
  printf "\n%s" "path to dotfiles.key: "
  read -r keyfile

  pushd "$HOME/.dotfiles"
  git crypt unlock "$keyfile"
  popd
fi
