#!/usr/bin/env bash

set -eo pipefail

# TODO: hooks don't seem to support interactive commands

# hooks are executed with pwd set to dirname of file
decryption_status_path="../../tag-encrypted/decryption-status"

if [ "$(cat "$decryption_status_path")" != "1" ]; then
  read -p "1Password subdomain: " opsubdomain
  read -p "1Password email: " opemail
  eval "$(op signin "$opsubdomain.1password.com" "$opemail")"

  keyfile=$(mktemp)
  op get document dotfiles.key > $keyfile

  pushd "$HOME/.dotfiles"
  git crypt unlock $keyfile
  popd
fi
