#!/usr/bin/env bash

set -eo pipefail

# hooks are executed with pwd set to dirname of file
decryption_status_path="../../tag-encrypted/decryption-status"

if [ "$(cat "$decryption_status_path")" != "1" ]; then
  printf "%s " "dotfiles.key: "
  read -s dotfiles_key
  keyfile=$(mktemp)
  echo "$dotfiles_key" > $keyfile

  pushd "$HOME/.dotfiles"
  git crypt unlock $keyfile
  popd
fi
