#!/usr/bin/env bash

set -eo pipefail

# TODO: replace with tag hooks
[[ "$OSTYPE" == "darwin"* ]] || exit

# hooks are executed with pwd set to dirname of file
dotfiles_root="$(cd ../.. && pwd -P)"

mkdir -p ~/Library/Fonts
if [ "$(cat "$dotfiles_root/tag-encrypted/decryption-status")" == "1" ]; then
  cp "$dotfiles_root"/tag-encrypted/fonts/* ~/Library/Fonts
fi
