#!/usr/bin/env bash

set -eo pipefail

# TODO: replace with tag hooks
[[ "$OSTYPE" == "darwin"* ]] || exit

dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null 2>&1 && pwd -P)"

mkdir -p ~/Library/Fonts
if [ "$(cat "$dotfiles_root/tag-encrypted/decryption-status")" == "1" ]; then
  find "$HOME/.local/share/fonts" -type f -exec cp '{}' ~/Library/Fonts \;
else
  echo "Fonts are not decrypted." >&2
  exit 1
fi
