#!/usr/bin/env bash

set -eo pipefail

# TODO: replace with tag hooks
[[ "$OSTYPE" == "darwin"* ]] || exit

mkdir -p ~/Library/Fonts
find -L "$HOME/.local/share/fonts" -type f -exec cp -n '{}' ~/Library/Fonts \;
