return {
  "airblade/vim-gitgutter",
  "christoomey/vim-tmux-navigator",
  { "dstein64/vim-startuptime", cmd = "StartupTime", },
  { "dhruvasagar/vim-table-mode", ft = {"markdown", "org"} },
  { "fatih/vim-go", ft = {"go", "gohtmltmpl"} },
  { "hashivim/vim-terraform", ft = {"hcl", "tf", "tfvars", "tfstate"} },
  { "janko-m/vim-test", lazy = true },
  "junegunn/fzf",
  "neovim/nvim-lspconfig",
  { "nvim-orgmode/orgmode", ft = {"org"} },
  { "nvim-tree/nvim-web-devicons", lazy = true },
  "nvim-treesitter/nvim-treesitter",
  "nvim-treesitter/nvim-treesitter-context",
  "tmhedberg/matchit",
  "tpope/vim-abolish",
  "tpope/vim-bundler",
  { "tpope/vim-dispatch", cmd = "Dispatch" },
  "tpope/vim-endwise",
  "tpope/vim-eunuch",
  "tpope/vim-fugitive",
  "tpope/vim-projectionist",
  "tpope/vim-repeat",
  "tpope/vim-rhubarb",
  "tpope/vim-rsi",
  "tpope/vim-surround",
  "tpope/vim-unimpaired",
  "tpope/vim-vinegar",
  "vim-airline/vim-airline",
  "vim-airline/vim-airline-themes",
  "vim-scripts/SyntaxRange",
  "vim-scripts/tComment",
  "w0rp/ale",
  "williamboman/mason-lspconfig.nvim",
  "williamboman/mason.nvim",
  "yssl/QFEnter",

  -- Completion
  "hrsh7th/nvim-cmp",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-path",
  "L3MON4D3/LuaSnip",
  "saadparwaiz1/cmp_luasnip",

  -- TypeScript
  "nvim-lua/plenary.nvim",
  {
    "pmizio/typescript-tools.nvim",
    dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
    ft = { "typescript", "javascript" },
  },
  {
    "dmmulroy/ts-error-translator.nvim",
    ft = { "typescript", "javascript" },
  },

  -- Formatting
  "stevearc/conform.nvim",
}
