return {
  "airblade/vim-gitgutter",
  "christoomey/vim-tmux-navigator",
  { "dstein64/vim-startuptime", cmd = "StartupTime", },
  { "dhruvasagar/vim-table-mode", ft = {"markdown", "org"} },
  { "fatih/vim-go", ft = {"go"} },
  { "hashivim/vim-terraform", ft = {"hcl", "tf", "tfvars", "tfstate"} },
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-cmdline",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-vsnip",
  "hrsh7th/nvim-cmp",
  "hrsh7th/vim-vsnip",
  { "janko-m/vim-test", lazy = true },
  {
    "L3MON4D3/LuaSnip",
    build = "make install_jsregexp"
  },
  "neovim/nvim-lspconfig",
  { "nvim-orgmode/orgmode", ft = {"org"} },
  { "nvim-tree/nvim-web-devicons", lazy = true },
  { "stevearc/dressing.nvim", event = "VeryLazy" },
  "tmhedberg/matchit",
  "tpope/vim-abolish",
  "tpope/vim-bundler",
  { "tpope/vim-dispatch", cmd = "Dispatch" },
  "tpope/vim-endwise",
  "tpope/vim-eunuch",
  "tpope/vim-fugitive",
  "tpope/vim-projectionist",
  "tpope/vim-repeat",
  "tpope/vim-rhubarb",
  "tpope/vim-rsi",
  "tpope/vim-surround",
  "tpope/vim-unimpaired",
  "tpope/vim-vinegar",
  "vim-airline/vim-airline",
  "vim-airline/vim-airline-themes",
  "vim-scripts/SyntaxRange",
  "vim-scripts/tComment",
  "w0rp/ale",
  "williamboman/mason-lspconfig.nvim",
  "williamboman/mason.nvim",
  "yssl/QFEnter",
}
