#!/usr/bin/env bash

# Setup vim-plug
if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Setup tmux terminfo
if ! infocmp tmux > /dev/null 2>&1; then
  tic -x -e tmux          $HOME/.config/terminfo/terminfo.src
  tic -x -e tmux-256color $HOME/.config/terminfo/terminfo.src
fi
