#!/usr/bin/env bash
if [ ! -e ~/.vim/bundle/YouCompleteMe/python/ycm/youcompleteme.pyc ]; then
  ~/.vim/bundle/YouCompleteMe/install.py --tern-completer --racer-completer
fi

if [ ! -d ~/.vim/bundle/tern_for_vim/node_modules ]; then
  npm install --prefix ~/.vim/bundle/tern_for_vim
fi

# Set up links for nvim
[[ -L $HOME/.vim/init.vim ]] || ln -s "$HOME/.vimrc" "$HOME/.vim/init.vim"
[[ -L $HOME/.config/nvim ]] || ln -s "$HOME/.vim" "$HOME/.config/nvim"
