#!/bin/sh
if [ ! -e /Library/Frameworks/MacFUSE.framework ]; then
  open $PWD/../assets/install-osxfuse.pkg
fi

if [ ! -e /Applications/VeraCrypt.app ]; then
  open $PWD/../assets/install-veracrypt.pkg
fi
