#! /bin/bash

echo "Loading latest thoughtbot/dotfiles..."
if [ ! -d "$HOME/.dotfiles-thoughtbot" ]; then
  git clone "https://github.com/thoughtbot/dotfiles.git" "$HOME/.dotfiles-thoughtbot"
else
  git -C "$HOME/.dotfiles-thoughtbot" pull
fi

number_of_cores=$(sysctl -n hw.ncpu)
git -C "$HOME/.dotfiles" submodule init
git -C "$HOME/.dotfiles" pull --recurse-submodules --jobs=$((number_of_cores - 1))
git -C "$HOME/.dotfiles" submodule update --recursive
