#!/usr/bin/env bash

set -e

if [ ! -f "$HOME/.dotfiles/.git/git-crypt/keys/default" ]; then
  read -p "Decrypt secrets using 1Password? (y/N) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    read -p "1Password subdomain: " opsubdomain
    read -p "1Password email: " opemail
    op signin "$opsubdomain.1password.com" "$opemail"

    keyfile=$(mktemp)
    op get document dotfiles.key > $keyfile

    pushd "$HOME/.dotfiles"
    git crypt unlock $keyfile
    popd
  fi
fi
