#!/usr/bin/env bash

set -e

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
  export PATH="/usr/local/bin:$PATH"
fi

if ! command -v mas >/dev/null; then
  brew install mas
fi

if [ ! -f /Library/Developer/CommandLineTools/usr/bin/git ]; then
  echo "Installing XCode..."
  sudo xcodebuild -license accept
fi

echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=$HOME/.dotfiles/Brewfile

echo "Cleaning up old Homebrew formulae ..."
brew cleanup
