#!/usr/bin/env bash

set -eo pipefail

set +e
case "$(/usr/bin/xcrun clang 2>&1)" in
  *"install"* )
    sudo /usr/bin/xcode-select --install
    sudo /usr/bin/xcodebuild -license accept
    ;;
  *"license"* )
    sudo /usr/bin/xcodebuild -license accept
esac
set -e

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
  export PATH="/usr/local/bin:$PATH"
fi

if ! command -v mas >/dev/null; then
  brew install mas
fi

echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=$HOME/.dotfiles/Brewfile --no-lock

echo "Cleaning up old Homebrew formulae ..."
brew cleanup
