#!/usr/bin/env bash

set -eo pipefail

dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd -P)"

if [[ "$OSTYPE" == "darwin"* ]]; then
  TAGS="mac"
  "$dotfiles_root"/hooks/pre-up/00-mac-homebrew
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  TAGS="linux"
else
  echo "Unsupported OS $OSTYPE"
  exit 1
fi

RCRC="$dotfiles_root/rcrc" rcup -t "$TAGS" -t "encrypted"

# TODO: ideally these would be hooks, but decrypt-git is interactive and
# hooks don't seem to support that
pushd "$dotfiles_root/hooks/todo" >/dev/null
./decrypt-git
./mac-fonts
popd >/dev/null
