#!/usr/bin/env bash

set -eo pipefail

dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd -P)"

dotfiles_os=

if [[ "$OSTYPE" == "darwin"* ]]; then
  dotfiles_os="mac"
elif grep -q UBUNTU_CODENAME /etc/os-release || (grep -qi microsoft /proc/version && [[ "$WSL_DISTRO_NAME" == "Ubuntu" ]]); then
  dotfiles_os="ubuntu"
  if ! dpkg -s build-essential >/dev/null 2>&1; then
    sudo apt-get update && sudo apt-get install build-essential -y
  fi
  if ! dpkg -s xcape >/dev/null 2>&1; then
    sudo apt-get update && sudo apt-get install xcape -y
  fi
  if ! dpkg -s zsh >/dev/null 2>&1; then
    sudo apt-get update && sudo apt-get install zsh -y
  fi
else
  echo "Unsupported OS $OSTYPE"
  exit 1
fi

"$dotfiles_root/script/bootstrap"
RCRC="$HOME/.dotfiles/rcrc" rcup -t "$dotfiles_os"

# TODO: ideally these would be hooks, but decrypt-git is interactive and
# hooks don't seem to support that
pushd "$dotfiles_root/hooks/todo" >/dev/null
./decrypt-git
./mac-fonts
popd >/dev/null
