from typing import Protocol

from papersync.model import Change, Item


class Source(Protocol):
    name: str

    def export(self, selector: str) -> list[Item]: ...
    def lookup(self, refs: list[str]) -> dict[str, Item]: ...


class Sink(Protocol):
    name: str

    def describe(self, change: Change) -> list[str]: ...
    def apply(self, changes: list[Change]) -> None: ...
    def verify(self, changes: list[Change]) -> list[str]: ...
    def mark_printed(self, refs: list[str]) -> None: ...
    def check(self) -> list[str]: ...
