#!/usr/bin/env bash

set -eo pipefail

pam_rea="auth       optional       pam_reattach.so"
pam_tid="auth       sufficient     pam_tid.so"

if ! grep "$pam_rea" /etc/pam.d/sudo >/dev/null; then
  sudo gsed -i "2i$pam_rea" /etc/pam.d/sudo
fi

if ! grep "$pam_tid" /etc/pam.d/sudo >/dev/null; then
  sudo gsed -i "/^$pam_rea/a $pam_tid" /etc/pam.d/sudo
fi
