#!/usr/bin/env bash

set -eo pipefail

PATH="$HOME/.rbenv/bin:$PATH"

echo "Configuring Ruby ..."

ruby_version="$(cat "$HOME/.ruby-version")"
eval "$(rbenv init -)"

if ! rbenv versions | grep -Fq "$ruby_version"; then
  rbenv install -s "$ruby_version"
fi

rbenv global "$ruby_version"
rbenv shell "$ruby_version"
gem update --system
gem install 'bundler'
if command -v nproc > /dev/null; then
  number_of_cores=$(nproc)
else
  number_of_cores=$(sysctl -n hw.ncpu)
fi
bundle config --global jobs $((number_of_cores - 1))
