#!/usr/bin/env bash

set -eo pipefail

# Add homebrew zsh shell
shell_path="/usr/local/bin/zsh"
if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
  echo "Adding '$shell_path' to /etc/shells"
  sudo sh -c "echo $shell_path >> /etc/shells"
fi
