#!/usr/bin/env bash

set -eo pipefail

base16_installed_templates="$(base16-manager list)"
if ! echo "$base16_installed_templates" | grep -q chriskempson/base16-shell; then
  base16-manager install chriskempson/base16-shell
fi

if ! echo "$base16_installed_templates" | grep -q chriskempson/base16-vim; then
  base16-manager install chriskempson/base16-vim
fi

base16-manager set eighties
