#!/usr/bin/env bash

set -eo pipefail

echo "Configuring Python for NeoVim ..."
pip3 install --user --upgrade neovim neovim-remote

echo "Updating remote vim plugins..."
nvim --headless -c 'UpdateRemotePlugins' -c 'qa'
