#!/usr/bin/env bash

set -eo pipefail

# Setup vim-plug
if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  nvim --headless +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim --headless +PlugInstall +qa
fi

echo "Updating vim plugins..."
nvim --headless +PlugUpdate +qa

echo "Configuring Python for NeoVim ..."
pip2 install neovim
pip3 install neovim
