#!/usr/bin/env bash

set -eo pipefail

echo "Setting up vim-plug..."
# Setup vim-plug
if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  nvim --headless -c 'PlugUpgrade' -c 'qa'
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim --headless -c 'PlugInstall' -c 'qa'
fi

echo "Updating vim plugins..."
nvim --headless -c 'PlugUpdate --sync' -c 'qa'

echo "Configuring Python for NeoVim ..."
pip3 install neovim

echo "Updating remote vim plugins..."
nvim --headless -c 'UpdateRemotePlugins' -c 'qa'
