tap "homebrew/bundle"
tap "homebrew/services"
tap "microsoft/git"
tap "nodenv/nodenv"
tap "railwaycat/emacsmacport"
tap "tinted-theming/tinted"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "fd" # emacs-mac
brew "findutils"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gh"
brew "gist"
brew "git"
brew "git-crypt"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "gnuplot" # emacs org-mode
brew "go"
brew "goles/battery/battery"
brew "graphviz" # emacs org-mode
brew "grep"
brew "highlight"
brew "htop"
brew "imagemagick" # emacs-mac
brew "jq"
brew "moreutils"
brew "neovim"
brew "netcat"
brew "node-build"
brew "nodenv"
brew "nodenv/nodenv/nodenv-default-packages"
brew "nodenv/nodenv/nodenv-package-json-engine"
brew "pandoc"
brew "pgformatter" # ale.vim
brew "pidof"
brew "pngpaste" # emacs org-mode
brew "poppler"
brew "protolint" # ale.vim
brew "pstree"
brew "pyenv"
brew "railwaycat/emacsmacport/emacs-mac", args: [
  "with-glib",
  "with-imagemagick",
  "with-librsvg",
  "with-native-compilation",
  "with-unlimited-select",
  "with-xwidgets",
]
brew "rbenv"
brew "rbenv-bundler"
brew "rbenv-ctags"
brew "rbenv-default-gems"
brew "ripgrep"
brew "ruby-build"
brew "ruby-install"
brew "rustup"
brew "shellcheck"
brew "skhd"
brew "socat"
brew "starship"
brew "tinted-theming/tinted/tinty"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman" # sorbet
brew "wget"
brew "yabai"
brew "zsh"
cask "1password-cli"
cask "font-fira-code"
cask "font-fontawesome"
cask "git-credential-manager"
cask "sf-symbols"
cask "wezterm"
